LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Models/ErrorViewModel.cs
using System;

namespace SEDC.Lamazon.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SEDC.Lamazon.Web.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Test(int id, string fName, string lName, int age, string message)
        {
            ViewBag.Id = id;
            ViewBag.fName = fName;
            ViewBag.lName = lName;
            ViewBag.age = age;
            ViewBag.message = message;


            return View();
        }
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Domain.Models;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.Web.Models;

namespace SEDC.Lamazon.Web.Controllers
{
    public class HomeController : Controller
    {

        protected readonly IProductService _productService;
        public HomeController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Index()
        {
            var products = _productService.GetAllProducts();
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Hello! Welcome to Lamazon online store! We are the cheapest store in the world!";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Email: lamazon@gmail.com";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.Web.Models;
using SEDC.Lamazon.WebModels.Enum;
using SEDC.Lamazon.WebModels.ViewModels;

namespace SEDC.Lamazon.Web.Controllers
{
    //TODO: Change all hardcoded userId in the controller
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        private readonly IProductService _productService;

        public OrderController(IOrderService orderService,
                               IUserService userService,
                               IProductService productService)
        {
            _orderService = orderService;
            _userService = userService;
            _productService = productService;
        }

        public IActionResult ListOrders()
        {
            //string userId = "3";
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
            List<OrderViewModel> userOrders = _orderService.GetAllOrders()
                                                            .Where(x => x.User.Id == user.Id)
                                                            .ToList();
            return View(userOrders);
        }

        public IActionResult ListAllOrders()
        {
            List<OrderViewModel> orders = _orderService.GetAllOrders().ToList();
            return View(orders);
        }

        public IActionResult OrderDetails(int orderId)
        {
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
            OrderViewModel order = _orderService.GetOrderById(orderId, user.Id);

            if(order.Id > 0)
            {
                return View("order", order);
            }
            else
            {
                return View("Error", new ErrorViewModel());
            }
        }

        public IActionResult Order()
        {
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
            OrderViewModel order = _orderService.GetCurrentOrder(user.Id);
            return View(order);
        }

        public IActionResult ApproveOrder(int orderId)
        {
            OrderViewModel order = _orderService.GetOrderById(orderId);
            _orderService.ChangeStatus(order.Id, order.User.Id, StatusTypeViewModel.Confirmed);
            return RedirectToAction("listallorders");
        }

        public IActionResult DeclineOrder(int orderId)
        {
            OrderViewModel order = _orderService.GetOrderById(orderId);
            _orderService.ChangeStatus(order.Id, order.User.Id, StatusTypeViewModel.Declined);
            return RedirectToAction("listallorders");
        }

        public IActionResult ChangeStatus(int orderId, int statusId)
        {
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
            _orderService.ChangeStatus(orderId, user.Id, (StatusTypeViewModel)statusId);
            return RedirectToAction("ListOrders");
        }

        public int AddProduct(int productId)
        {
            UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
            OrderViewModel order = _orderService.GetCurrentOrder(user.Id);

            int result = _orderService.AddProduct(order.Id, productId, user.Id);

            if(result >= 0)
            {
                return result;
            }
            else
            {
                string message = "Something bad happened! Please contact support!";
                return result;
            }
        }
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.Services.Services;
using SEDC.Lamazon.WebModels.ViewModels;

namespace SEDC.Lamazon.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public IActionResult Products()
        {
            List<ProductViewModel> products = _productService.GetAllProducts().ToList();
            return View(products);
        }
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.WebModels.ViewModels;

namespace SEDC.Lamazon.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public IActionResult LogIn()
        {
            LoginViewModel model = new LoginViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult LogIn(LoginViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isAdmin;
                    _userService.Login(model, out isAdmin);
                    if (isAdmin)
                    {
                        return RedirectToAction("listallorders", "order");
                    }
                    else
                    {
                        return RedirectToAction("products", "product");
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return View(model);
        }

        public IActionResult Register()
        {
            RegisterViewModel model = new RegisterViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                _userService.Register(model);
                return RedirectToAction("products", "product");
            }
            return View(model);
        }

        public IActionResult LogOut()
        {
            _userService.Logout();
            return RedirectToAction("index", "home");
        }
    }
}

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Demo/Test.cshtml
@{
    ViewData["Title"] = "Test";
}

<h2>Test</h2>

<h3>ID: @ViewBag.Id</h3>
<h3>Firstname: @ViewBag.fName</h3>
<h3>Lastname: @ViewBag.lName</h3>
<h3>Age: @ViewBag.age</h3>
<h3>@ViewBag.fName whants to say: @ViewBag.message</h3>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Lamazon MK<br />
    Kachanichki pat bb.<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:support@lamazon.com">support@lamazon.com</a><br />
</address>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-3"></div>    
    <div class="col-md-6">
        <h2>Here will go the logo image</h2>
    </div>    
    <div class="col-md-3"></div>    
</div>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Order/ListAllOrders.cshtml
@model List<OrderViewModel>
@{
    ViewData["Title"] = "ListAllOrders";
}

<h2>All users' orders</h2>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Status</th>
            <th scope="col">Price</th>
            <th scope="col">User full name</th>
            <th scope="col">Products</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.Id</td>
                <td>@order.Status</td>
                <td>@order.Price</td>
                <td>@order.User.Fullname</td>
                @{
                    int i = 0;
                }
                <td>
                    @foreach (var product in order.Products)
                    {
                        i++;
                        if (order.Products.Count() == i)
                        {
                            <span>@product.Name</span>
                        }
                        else
                        {
                            <span>@product.Name,</span>
                        }
                    }
                </td>
                @if (order.Status == StatusTypeViewModel.Pending)
                {
                    <td>
                        <a asp-action="approveorder" asp-controller="Order" asp-route-orderId="@order.Id" class="btn btn-primary">Approve</a>
                        <a asp-action="declineorder" asp-controller="Order" asp-route-orderId="@order.Id" class="btn btn-primary">Decline</a>
                    </td>
                }
                else if (order.Status == StatusTypeViewModel.Confirmed)
                {
                    <td>Waiting to be delivered!</td>
                }
                else if (order.Status == StatusTypeViewModel.Declined)
                {
                    <td>You have successfully declined this order!</td>
                }
                else
                {
                    <td>Waiting for customer!</td>
                }
            </tr>
        }
    </tbody>
</table>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Order/ListOrders.cshtml
@model List<OrderViewModel>
@{
    ViewData["Title"] = "ListOrders";
}

<h2>Orders history</h2>


<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Status</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
        <tr>
            <td>@order.Id</td>
            <td>@order.Status</td>
            <td>@order.Price</td>
            <td>
                <a asp-action="OrderDetails" asp-controller="Order" asp-route-orderId="@order.Id" class="btn btn-primary">Details</a>
            </td>
        </tr>
        }
    </tbody>
</table>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Order/Order.cshtml
@model OrderViewModel
@{
    ViewData["Title"] = "Order";
}

<h1>Order</h1>

<div class="container">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <label asp-for="User.Fullname"></label>
                <p>@Model.User.Fullname</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Id"></label>
                <p>@Model.Id</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Status"></label>
                <p>@Model.Status</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Price"></label>
                <p>@Model.Price $</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <label asp-for="Products"></label>
                @if (Model.Products.Count() > 0)
                {
                    <ul>
                        @foreach (var product in Model.Products)
                        {
                            <li>@product.Name - @product.Price $</li>
                        }
                    </ul>
                   @if(Model.Status == StatusTypeViewModel.Init)
                   {
                       <a asp-controller="Order" asp-action="ChangeStatus" asp-route-orderId="@Model.Id" asp-route-statusId="1" class="btn btn-primary">Proceed</a>
                   }
                }
                else
                {
                    <p>Cart is empty!</p>
                }
            </div>
        </div>
    </div>
</div>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lamazon Store</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lamazon Store</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>


                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Order" asp-action="ListAllOrders">All orders</a></li>
                    }
                    else
                    {
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a asp-area="" asp-controller="Order" asp-action="Order">Current order</a></li>
                            <li><a asp-area="" asp-controller="Order" asp-action="ListOrders">My orders</a></li>
                            <li><a asp-area="" asp-controller="Product" asp-action="Products">Products</a></li>
                        }
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="align-right">
                            <a asp-controller="User" asp-action="LogOut">Logout</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="align-right">
                            <a asp-controller="User" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2020 - Lamazon Store</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/User/LogIn.cshtml
@model LoginViewModel
@{
    ViewData["Title"] = "LogIn";
}

<h2>Welcome!</h2>

<div class="container">
    <div>
        <h2>Please login!</h2>
        <div class="col-md-12">
            <form asp-action="Login" asp-controller="User" method="post">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Username"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user"></span></span>
                            <input class="form-control" type="text" asp-for="Username" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Password"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock"></span></span>
                            <input class="form-control" type="password" asp-for="Password" />
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6">
                <h4>
                    Don't have an account? <a asp-action="Register" asp-controller="User"> Register here </a> and proceed buying!
                </h4>
            </div>
        </div>
    </div>
</div>

LamazonApp/SEDC.Lamazon/SEDC.Lamazon.Web/Views/User/Register.cshtml
@model RegisterViewModel
@{
    ViewData["Title"] = "Register";
}

<h2>Register</h2>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Register" asp-controller="User" method="post">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Firstname"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user"></span></span>
                            <input class="form-control" type="text" asp-for="Firstname" placeholder="Firstname" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Lastname"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user"></span></span>
                            <input class="form-control" type="text" asp-for="Lastname" placeholder="Lastname" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Email"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-envelope"></span></span>
                            <input class="form-control" type="email" asp-for="Email" placeholder="Email" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Address"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-home"></span></span>
                            <input class="form-control" type="text" asp-for="Address" placeholder="Address" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Username"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-user"></span></span>
                            <input class="form-control" type="text" asp-for="Username" placeholder="Username" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="Password"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock"></span></span>
                            <input class="form-control" type="password" asp-for="Password" placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-4">
                        <label asp-for="ConfirmPassword"></label>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-lock"></span></span>
                            <input class="form-control" type="text" asp-for="ConfirmPassword" placeholder="Confirm password" />
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-5"></div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>